object Versions {
    const val kotlinGradlePlugin = "1.7.20"
    const val hiltVersion = "2.44.2"
    const val gradlePluginVersion = "7.3.1"
    const val kotlinVersion = "1.5.31"

    const val coreKTXVersion = "1.9.0"
    const val composeCompilerVersion = "1.3.2"
    const val composeVersion = "1.3.1"
    const val activityComposeVersion = "1.6.1"
    const val navigationVersion = "2.5.3"
    const val room_version = "2.3.0"
    const val constraintlayoutVersion = "2.1.4"
    const val lifecycleExtensions_version = "2.2.0"
    const val lifecycleCommonJava_version = "2.3.1"
    const val androidArchitecture_version = "2.2.0"
    const val materialVersion = "1.4.0"
    const val appCompatVersion = "1.5.1"
    const val googleMaterial_version = "1.4.0"
    const val retrofitVersion = "2.9.0"
    const val gsonVersion = "2.10"
    const val okHttpVersion = "4.10.0"
    const val httpLoggingInterceptorVersion = "4.10.0"
    const val coroutinesVersion = "1.3.9"
    const val lifecycleViewModelVersion = "2.5.1"
    const val mockito_version = "3.12.4"
    const val jUnitVersion = "4.13.2"
    const val jUnitAndroidExt = "1.1.4"
    const val gsonConverterVersion = "2.9.0"
    const val timberVersion = "5.0.1"
    const val accompanishVersion = "5.0.1"
    const val coilVersion = "2.2.2"
    const val viewModelComposeVersion = "2.5.1"
    const val mockkVersion = "1.13.2"
    const val robolectric = "4.8"

}